apiVersion: apps/v1 

kind: Deployment

metadata: 
  name: dep
  


spec:
  selector:
    matchLabels:
      label-name-1: pod1
  replicas: 3
  template: 
    metadata:
      name: my-first-web
      labels:
        label-name-1: pod1
    spec:
      containers:
        - name: nginx-container
          image: mostafashaheen123/nginximage
          ports: 
            - containerPort: 80
          imagePullPolicy: IfNotPresent
           